name: Terraform GCP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with GCP
        run: gcloud auth application-default login
      - name: Apply Terraform configuration
        run: terraform apply
